# Generated by Django 5.0.3 on 2024-10-02 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardekho_app', '0003_showroomlist_alter_carlist_carnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroomlist',
            name='showroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showrooms', to='cardekho_app.carlist'),
        ),
    ]
