# Generated by Django 5.0.3 on 2024-10-02 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardekho_app', '0004_showroomlist_showroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showroomlist',
            name='showroom',
        ),
        migrations.AddField(
            model_name='carlist',
            name='showroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showrooms', to='cardekho_app.showroomlist'),
        ),
    ]
