# Generated by Django 5.0.3 on 2024-10-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardekho_app', '0008_alter_review_apiuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='apiuser',
        ),
    ]
